### ISSUE TITLE
はじめての Django アプリ作成、その 1

### ISSUE THREAD

**Issue by Parasuatene** [kyuta8/Dokkan#3]

**Comment by kyuta8** [comment]
プロジェクトの作成
`$ django-admin startproject [プロジェクト名]`


作成したプロジェクトのディレクトリ構造
```
[プロジェクト名]/  
    manage.py  
    [プロジェクト名]/  
        __init__.py  
        settings.py  
        urls.py  
        asgi.py  
        wsgi.py  
```

- 外側の **[プロジェクト名]/** ルートディレクトリは、プロジェクトのコンテナです。その名前は Django にとって重要ではありません。任意の名前に変更できます。

- **manage.py**: Django プロジェクトに対する様々な操作を行うためのコマンドラインユーティリティです｡詳しくは django-admin と manage.py 内の manage.py を参照してください｡

- 内側の **[プロジェクト名]/** ディレクトリは、このプロジェクトの実際の Python パッケージです。この名前が Python パッケージの名前であり、 import の際に 使用する名前です (例えば import [プロジェクト名].urls) 。

- **[プロジェクト名]/__init__.py**: このディレクトリが Python パッケージであることを Python に知らせるための空のファイルです。Python の初心者は、 Python の公式 ドキュメントの more about packages を読んで下さい。

- **[プロジェクト名]/settings.py**: Django プロジェクトの設定ファイルです。 設定の仕組みは Djangoの設定 を参照してください。

- **[プロジェクト名]/urls.py**: Django プロジェクトの URL 宣言、いうなれば Django サイトにおける「目次」に相当します。詳しくは URL ディスパッチャ を参照 してください。

- **[プロジェクト名]/asgi.py**: プロジェクトを提供する ASGI 互換 Web サーバーのエントリポイント。詳細については How to deploy with ASGI を参照してください。

- **[プロジェクト名]/wsgi.py**: プロジェクトをサーブするためのWSGI互換Webサーバーとのエントリーポイントです。詳細は WSGI とともにデプロイするには を参照してください。

**Comment by kyuta8** [comment]
## アプリケーションの作成
アプリケーションモジュールのセットアップ

`$ python manage.py startapp [アプリ名]`

作成したアプリのディレクトリ構造
```
[アプリ名]/
    __init__.py
    admin.py
    apps.py
    migrations/
        __init__.py
    models.py
    tests.py
    views.py
```

- **models.py**: サイト内で扱うデータのクラスインスタンスの記述を行うファイルです。

- **views.py**: サイト内の処理絵お記述するファイルです。

**Comment by kyuta8** [comment]
## Viewの作成
サイトの表示を行うためには，**[アプリ名]/views.py** の編集と **[アプリ名]/** 以下に **urls.py** の作成が必要になります．

**[アプリ名]/views.py 内のコード例**
```
from django.http import HttpResponse

def index(request):
    return HttpResponse("Hello, world. You're at the polls index.")
```

- HTTPリクエストに対して文字列のレスポンスを行う処理

**[アプリ名]/urls.py**
```
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
]
```

- **[アプリ名]/views.py** を読み出し，URLと対応付け

**[プロジェクト名]/urls.py**
```
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('[アプリ名]/', include('[アプリ名].urls')),
    path('admin/', admin.site.urls),
]
```

- **[アプリ名]/urls.py** のモジュールをルートURLに反映

---

- **include()**: include関数は他のURLの参照を可能にする関数です．関数内に記述されたモジュールを自動で検索し，該当するモジュールまでのPathの自動補完を行う．

**Comment by kyuta8** [comment]
## サイトへのアクセス
サーバの立ち上げ
```
$ python manage.py runserver
Performing system checks...

System check identified no issues (0 silenced).

You have unapplied migrations; your app may not work properly until they are applied.
Run 'python manage.py migrate' to apply them.

3月 04, 2020 - 15:50:53
Django version 3.0, using settings 'mysite.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
```

サイトへのアクセス #4
